"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        my_set = set()
        for x in t:
            if x in my_set:
                continue
            if s.count(x) != t.count(x):
                return x
            my_set.add(x)

cases = [("abc","abbcc",),
         ("ccd", "ccdd",),
         ("abc", "abd",)
         ]
sol = Solution()
print [sol.findTheDifference(x[0],x[1]) for x in cases ]